name: Backup master to main
on:
  push:
    branches: [master]

jobs:
  backup:
    runs-on: ubuntu-latest
    environment: backup-approval  # Requires manual approval
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Backup master to main
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch --all
          git checkout -B main origin/master
          git push origin main --force
