name: Backup master to main
on:
  push:
    branches: [ master ]
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Force-update main to match master
        run: |
          git config --global user.name "GitHub Actions Backup"
          git config --global user.email "actions@github.com"
          git fetch origin master
          git checkout main
          git reset --hard origin/master
          git push origin main --force
