name: Backup master to main
on:
  push:
    branches: [ master ]
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetches all branches

      - name: Force-update main to match master
        run: |
          git config --global user.name "GitHub Actions Backup"
          git config --global user.email "actions@github.com"

          # Check if main exists, create if not
          if ! git show-ref --verify --quiet refs/heads/main; then
            git branch main origin/master
          fi

          git checkout main
          git reset --hard origin/master
          git push origin main --force
